#!/bin/bash
# Open Fit Self-Hosted Setup Script
# Generates all required environment variables for self-hosting

echo "================================================"
echo "  Open Fit - Self-Hosted Setup"
echo "================================================"
echo ""

# F8: Check for required tools
if ! command -v docker &> /dev/null; then
    echo "Error: docker is not installed or not in PATH"
    exit 1
fi

if ! command -v openssl &> /dev/null; then
    echo "Error: openssl is not installed or not in PATH"
    exit 1
fi

# Check if .env already exists
if [ -f .env ]; then
    read -p ".env file already exists. Overwrite? (y/N): " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

echo "[1/4] Generating INSTANCE_SECRET..."
INSTANCE_SECRET=$(openssl rand -hex 32)

if [ -z "$INSTANCE_SECRET" ]; then
    echo "Error: Failed to generate INSTANCE_SECRET"
    exit 1
fi

echo "[2/4] Generating CONVEX_SELF_HOSTED_ADMIN_KEY..."
# F8: Show errors instead of suppressing with 2>/dev/null
ADMIN_KEY=$(docker run --rm -e INSTANCE_SECRET="$INSTANCE_SECRET" --entrypoint ./generate_admin_key.sh ghcr.io/get-convex/convex-backend:latest)

if [ -z "$ADMIN_KEY" ]; then
    echo "Error: Failed to generate admin key"
    exit 1
fi

echo "[3/4] Generating JWT keys..."
# F2: Fixed - using explicit newline replacement that works correctly
JWT_OUTPUT=$(docker run --rm node:lts-slim node -e '
const crypto = require("crypto");

async function generateKeys() {
    const { subtle } = crypto.webcrypto;

    const keyPair = await subtle.generateKey(
        {
            name: "RSASSA-PKCS1-v1_5",
            modulusLength: 2048,
            publicExponent: new Uint8Array([1, 0, 1]),
            hash: "SHA-256",
        },
        true,
        ["sign", "verify"]
    );

    const privateKeyBuffer = await subtle.exportKey("pkcs8", keyPair.privateKey);
    const privateKeyBase64 = Buffer.from(privateKeyBuffer).toString("base64");
    const privateKeyPem = "-----BEGIN PRIVATE KEY----- " +
        privateKeyBase64.match(/.{1,64}/g).join(" ") +
        " -----END PRIVATE KEY-----";

    const publicJwk = await subtle.exportKey("jwk", keyPair.publicKey);
    publicJwk.use = "sig";
    publicJwk.alg = "RS256";

    const jwks = JSON.stringify({ keys: [publicJwk] });

    console.log("JWT_PRIVATE_KEY=" + privateKeyPem);
    console.log("JWKS=" + jwks);
}

generateKeys().catch(e => { console.error(e); process.exit(1); });
')

if [ -z "$JWT_OUTPUT" ]; then
    echo "Error: Failed to generate JWT keys"
    exit 1
fi

# Parse JWT output
JWT_PRIVATE_KEY=$(echo "$JWT_OUTPUT" | grep "^JWT_PRIVATE_KEY=" | cut -d'=' -f2-)
JWKS=$(echo "$JWT_OUTPUT" | grep "^JWKS=" | cut -d'=' -f2-)

if [ -z "$JWT_PRIVATE_KEY" ] || [ -z "$JWKS" ]; then
    echo "Error: Failed to parse JWT keys"
    exit 1
fi

echo "[4/4] Writing .env file..."

cat > .env << EOF
# Open Fit Self-Hosted Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Convex Backend Configuration
INSTANCE_SECRET=${INSTANCE_SECRET}
CONVEX_SELF_HOSTED_ADMIN_KEY=${ADMIN_KEY}

# JWT Authentication Keys
JWT_PRIVATE_KEY='${JWT_PRIVATE_KEY}'
JWKS='${JWKS}'

# Public Convex URL - what the browser uses to connect to Convex
# Change this if you're exposing Convex via a reverse proxy
NEXT_PUBLIC_CONVEX_URL=http://localhost:3210

# Optional: Change the app port (default: 3000)
# APP_PORT=3000
EOF

echo ""
echo "================================================"
echo "  Setup Complete!"
echo "================================================"
echo ""
echo "Your .env file has been created with all required keys."
echo ""
echo "Next steps:"
echo "  1. (Optional) Edit .env to customize PUBLIC_CONVEX_URL or APP_PORT"
echo "  2. Start the application:"
echo ""
echo "     docker compose up -d"
echo ""
echo "The database will initialize automatically on first boot."
echo "Open http://localhost:3000 and create your account!"
echo ""
