// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkoutRouteImport } from "./routes/workout";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as RoutinesRouteImport } from "./routes/routines";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as LogsRouteImport } from "./routes/logs";
import { Route as ExercisesRouteImport } from "./routes/exercises";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiUserProfileRouteImport } from "./routes/api/user-profile";
import { Route as ApiUploadRouteImport } from "./routes/api/upload";
import { Route as ApiSetsRouteImport } from "./routes/api/sets";
import { Route as ApiSetGroupsRouteImport } from "./routes/api/set-groups";
import { Route as ApiSessionsRouteImport } from "./routes/api/sessions";
import { Route as ApiRoutinesRouteImport } from "./routes/api/routines";
import { Route as ApiRoutineDaysRouteImport } from "./routes/api/routine-days";
import { Route as ApiGymsRouteImport } from "./routes/api/gyms";
import { Route as ApiExercisesRouteImport } from "./routes/api/exercises";
import { Route as ApiUploadsSplatRouteImport } from "./routes/api/uploads.$";
import { Route as ApiStorageSplatRouteImport } from "./routes/api/storage.$";
import { Route as ApiSetsReorderRouteImport } from "./routes/api/sets/reorder";
import { Route as ApiSetsIdRouteImport } from "./routes/api/sets.$id";
import { Route as ApiSetGroupsReorderRouteImport } from "./routes/api/set-groups/reorder";
import { Route as ApiSetGroupsIdRouteImport } from "./routes/api/set-groups.$id";
import { Route as ApiSessionsCurrentRouteImport } from "./routes/api/sessions/current";
import { Route as ApiSessionsIdRouteImport } from "./routes/api/sessions.$id";
import { Route as ApiRoutinesIdRouteImport } from "./routes/api/routines.$id";
import { Route as ApiRoutineDaysIdRouteImport } from "./routes/api/routine-days.$id";
import { Route as ApiLookupsUnitsRouteImport } from "./routes/api/lookups/units";
import { Route as ApiLookupsMuscleGroupsRouteImport } from "./routes/api/lookups/muscle-groups";
import { Route as ApiLookupsEquipmentRouteImport } from "./routes/api/lookups/equipment";
import { Route as ApiLookupsCategoriesRouteImport } from "./routes/api/lookups/categories";
import { Route as ApiGymsIdRouteImport } from "./routes/api/gyms.$id";
import { Route as ApiExercisesSimilarRouteImport } from "./routes/api/exercises/similar";
import { Route as ApiExercisesSearchRouteImport } from "./routes/api/exercises/search";
import { Route as ApiExercisesIdRouteImport } from "./routes/api/exercises.$id";
import { Route as ApiDashboardStatsRouteImport } from "./routes/api/dashboard/stats";
import { Route as ApiDashboardRecentSessionsRouteImport } from "./routes/api/dashboard/recent-sessions";
import { Route as ApiAuthProvidersRouteImport } from "./routes/api/auth/providers";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as ApiAdminUsersRouteImport } from "./routes/api/admin/users";
import { Route as ApiAdminLookupsRouteImport } from "./routes/api/admin/lookups";
import { Route as ApiAdminExercisesRouteImport } from "./routes/api/admin/exercises";
import { Route as ApiAdminCheckRouteImport } from "./routes/api/admin/check";
import { Route as ApiSetGroupsIdReplaceExerciseRouteImport } from "./routes/api/set-groups.$id.replace-exercise";
import { Route as ApiSetGroupsIdBulkEditRouteImport } from "./routes/api/set-groups.$id.bulk-edit";
import { Route as ApiAdminUsersIdRouteImport } from "./routes/api/admin/users.$id";
import { Route as ApiAdminLookupsIdRouteImport } from "./routes/api/admin/lookups.$id";
import { Route as ApiAdminExercisesIdRouteImport } from "./routes/api/admin/exercises.$id";
import type { getRouter } from "./router.tsx";

const WorkoutRoute = WorkoutRouteImport.update({
  id: "/workout",
  path: "/workout",
  getParentRoute: () => rootRouteImport,
} as any);
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const RoutinesRoute = RoutinesRouteImport.update({
  id: "/routines",
  path: "/routines",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any);
const ExercisesRoute = ExercisesRouteImport.update({
  id: "/exercises",
  path: "/exercises",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: "/api/user-profile",
  path: "/api/user-profile",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: "/api/upload",
  path: "/api/upload",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetsRoute = ApiSetsRouteImport.update({
  id: "/api/sets",
  path: "/api/sets",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetGroupsRoute = ApiSetGroupsRouteImport.update({
  id: "/api/set-groups",
  path: "/api/set-groups",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: "/api/sessions",
  path: "/api/sessions",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRoutinesRoute = ApiRoutinesRouteImport.update({
  id: "/api/routines",
  path: "/api/routines",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRoutineDaysRoute = ApiRoutineDaysRouteImport.update({
  id: "/api/routine-days",
  path: "/api/routine-days",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiGymsRoute = ApiGymsRouteImport.update({
  id: "/api/gyms",
  path: "/api/gyms",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiExercisesRoute = ApiExercisesRouteImport.update({
  id: "/api/exercises",
  path: "/api/exercises",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: "/api/uploads/$",
  path: "/api/uploads/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: "/api/storage/$",
  path: "/api/storage/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetsReorderRoute = ApiSetsReorderRouteImport.update({
  id: "/reorder",
  path: "/reorder",
  getParentRoute: () => ApiSetsRoute,
} as any);
const ApiSetsIdRoute = ApiSetsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiSetsRoute,
} as any);
const ApiSetGroupsReorderRoute = ApiSetGroupsReorderRouteImport.update({
  id: "/reorder",
  path: "/reorder",
  getParentRoute: () => ApiSetGroupsRoute,
} as any);
const ApiSetGroupsIdRoute = ApiSetGroupsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiSetGroupsRoute,
} as any);
const ApiSessionsCurrentRoute = ApiSessionsCurrentRouteImport.update({
  id: "/current",
  path: "/current",
  getParentRoute: () => ApiSessionsRoute,
} as any);
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiSessionsRoute,
} as any);
const ApiRoutinesIdRoute = ApiRoutinesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiRoutinesRoute,
} as any);
const ApiRoutineDaysIdRoute = ApiRoutineDaysIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiRoutineDaysRoute,
} as any);
const ApiLookupsUnitsRoute = ApiLookupsUnitsRouteImport.update({
  id: "/api/lookups/units",
  path: "/api/lookups/units",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiLookupsMuscleGroupsRoute = ApiLookupsMuscleGroupsRouteImport.update({
  id: "/api/lookups/muscle-groups",
  path: "/api/lookups/muscle-groups",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiLookupsEquipmentRoute = ApiLookupsEquipmentRouteImport.update({
  id: "/api/lookups/equipment",
  path: "/api/lookups/equipment",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiLookupsCategoriesRoute = ApiLookupsCategoriesRouteImport.update({
  id: "/api/lookups/categories",
  path: "/api/lookups/categories",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiGymsIdRoute = ApiGymsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiGymsRoute,
} as any);
const ApiExercisesSimilarRoute = ApiExercisesSimilarRouteImport.update({
  id: "/similar",
  path: "/similar",
  getParentRoute: () => ApiExercisesRoute,
} as any);
const ApiExercisesSearchRoute = ApiExercisesSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => ApiExercisesRoute,
} as any);
const ApiExercisesIdRoute = ApiExercisesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiExercisesRoute,
} as any);
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: "/api/dashboard/stats",
  path: "/api/dashboard/stats",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiDashboardRecentSessionsRoute =
  ApiDashboardRecentSessionsRouteImport.update({
    id: "/api/dashboard/recent-sessions",
    path: "/api/dashboard/recent-sessions",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: "/api/auth/providers",
  path: "/api/auth/providers",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: "/api/admin/users",
  path: "/api/admin/users",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAdminLookupsRoute = ApiAdminLookupsRouteImport.update({
  id: "/api/admin/lookups",
  path: "/api/admin/lookups",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAdminExercisesRoute = ApiAdminExercisesRouteImport.update({
  id: "/api/admin/exercises",
  path: "/api/admin/exercises",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAdminCheckRoute = ApiAdminCheckRouteImport.update({
  id: "/api/admin/check",
  path: "/api/admin/check",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSetGroupsIdReplaceExerciseRoute =
  ApiSetGroupsIdReplaceExerciseRouteImport.update({
    id: "/replace-exercise",
    path: "/replace-exercise",
    getParentRoute: () => ApiSetGroupsIdRoute,
  } as any);
const ApiSetGroupsIdBulkEditRoute = ApiSetGroupsIdBulkEditRouteImport.update({
  id: "/bulk-edit",
  path: "/bulk-edit",
  getParentRoute: () => ApiSetGroupsIdRoute,
} as any);
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiAdminUsersRoute,
} as any);
const ApiAdminLookupsIdRoute = ApiAdminLookupsIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiAdminLookupsRoute,
} as any);
const ApiAdminExercisesIdRoute = ApiAdminExercisesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiAdminExercisesRoute,
} as any);

export type FileRoutesByFullPath = {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/exercises": typeof ExercisesRoute;
  "/logs": typeof LogsRoute;
  "/register": typeof RegisterRoute;
  "/routines": typeof RoutinesRoute;
  "/signin": typeof SigninRoute;
  "/workout": typeof WorkoutRoute;
  "/api/exercises": typeof ApiExercisesRouteWithChildren;
  "/api/gyms": typeof ApiGymsRouteWithChildren;
  "/api/routine-days": typeof ApiRoutineDaysRouteWithChildren;
  "/api/routines": typeof ApiRoutinesRouteWithChildren;
  "/api/sessions": typeof ApiSessionsRouteWithChildren;
  "/api/set-groups": typeof ApiSetGroupsRouteWithChildren;
  "/api/sets": typeof ApiSetsRouteWithChildren;
  "/api/upload": typeof ApiUploadRoute;
  "/api/user-profile": typeof ApiUserProfileRoute;
  "/api/admin/check": typeof ApiAdminCheckRoute;
  "/api/admin/exercises": typeof ApiAdminExercisesRouteWithChildren;
  "/api/admin/lookups": typeof ApiAdminLookupsRouteWithChildren;
  "/api/admin/users": typeof ApiAdminUsersRouteWithChildren;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/auth/providers": typeof ApiAuthProvidersRoute;
  "/api/dashboard/recent-sessions": typeof ApiDashboardRecentSessionsRoute;
  "/api/dashboard/stats": typeof ApiDashboardStatsRoute;
  "/api/exercises/$id": typeof ApiExercisesIdRoute;
  "/api/exercises/search": typeof ApiExercisesSearchRoute;
  "/api/exercises/similar": typeof ApiExercisesSimilarRoute;
  "/api/gyms/$id": typeof ApiGymsIdRoute;
  "/api/lookups/categories": typeof ApiLookupsCategoriesRoute;
  "/api/lookups/equipment": typeof ApiLookupsEquipmentRoute;
  "/api/lookups/muscle-groups": typeof ApiLookupsMuscleGroupsRoute;
  "/api/lookups/units": typeof ApiLookupsUnitsRoute;
  "/api/routine-days/$id": typeof ApiRoutineDaysIdRoute;
  "/api/routines/$id": typeof ApiRoutinesIdRoute;
  "/api/sessions/$id": typeof ApiSessionsIdRoute;
  "/api/sessions/current": typeof ApiSessionsCurrentRoute;
  "/api/set-groups/$id": typeof ApiSetGroupsIdRouteWithChildren;
  "/api/set-groups/reorder": typeof ApiSetGroupsReorderRoute;
  "/api/sets/$id": typeof ApiSetsIdRoute;
  "/api/sets/reorder": typeof ApiSetsReorderRoute;
  "/api/storage/$": typeof ApiStorageSplatRoute;
  "/api/uploads/$": typeof ApiUploadsSplatRoute;
  "/api/admin/exercises/$id": typeof ApiAdminExercisesIdRoute;
  "/api/admin/lookups/$id": typeof ApiAdminLookupsIdRoute;
  "/api/admin/users/$id": typeof ApiAdminUsersIdRoute;
  "/api/set-groups/$id/bulk-edit": typeof ApiSetGroupsIdBulkEditRoute;
  "/api/set-groups/$id/replace-exercise": typeof ApiSetGroupsIdReplaceExerciseRoute;
};
export type FileRoutesByTo = {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/exercises": typeof ExercisesRoute;
  "/logs": typeof LogsRoute;
  "/register": typeof RegisterRoute;
  "/routines": typeof RoutinesRoute;
  "/signin": typeof SigninRoute;
  "/workout": typeof WorkoutRoute;
  "/api/exercises": typeof ApiExercisesRouteWithChildren;
  "/api/gyms": typeof ApiGymsRouteWithChildren;
  "/api/routine-days": typeof ApiRoutineDaysRouteWithChildren;
  "/api/routines": typeof ApiRoutinesRouteWithChildren;
  "/api/sessions": typeof ApiSessionsRouteWithChildren;
  "/api/set-groups": typeof ApiSetGroupsRouteWithChildren;
  "/api/sets": typeof ApiSetsRouteWithChildren;
  "/api/upload": typeof ApiUploadRoute;
  "/api/user-profile": typeof ApiUserProfileRoute;
  "/api/admin/check": typeof ApiAdminCheckRoute;
  "/api/admin/exercises": typeof ApiAdminExercisesRouteWithChildren;
  "/api/admin/lookups": typeof ApiAdminLookupsRouteWithChildren;
  "/api/admin/users": typeof ApiAdminUsersRouteWithChildren;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/auth/providers": typeof ApiAuthProvidersRoute;
  "/api/dashboard/recent-sessions": typeof ApiDashboardRecentSessionsRoute;
  "/api/dashboard/stats": typeof ApiDashboardStatsRoute;
  "/api/exercises/$id": typeof ApiExercisesIdRoute;
  "/api/exercises/search": typeof ApiExercisesSearchRoute;
  "/api/exercises/similar": typeof ApiExercisesSimilarRoute;
  "/api/gyms/$id": typeof ApiGymsIdRoute;
  "/api/lookups/categories": typeof ApiLookupsCategoriesRoute;
  "/api/lookups/equipment": typeof ApiLookupsEquipmentRoute;
  "/api/lookups/muscle-groups": typeof ApiLookupsMuscleGroupsRoute;
  "/api/lookups/units": typeof ApiLookupsUnitsRoute;
  "/api/routine-days/$id": typeof ApiRoutineDaysIdRoute;
  "/api/routines/$id": typeof ApiRoutinesIdRoute;
  "/api/sessions/$id": typeof ApiSessionsIdRoute;
  "/api/sessions/current": typeof ApiSessionsCurrentRoute;
  "/api/set-groups/$id": typeof ApiSetGroupsIdRouteWithChildren;
  "/api/set-groups/reorder": typeof ApiSetGroupsReorderRoute;
  "/api/sets/$id": typeof ApiSetsIdRoute;
  "/api/sets/reorder": typeof ApiSetsReorderRoute;
  "/api/storage/$": typeof ApiStorageSplatRoute;
  "/api/uploads/$": typeof ApiUploadsSplatRoute;
  "/api/admin/exercises/$id": typeof ApiAdminExercisesIdRoute;
  "/api/admin/lookups/$id": typeof ApiAdminLookupsIdRoute;
  "/api/admin/users/$id": typeof ApiAdminUsersIdRoute;
  "/api/set-groups/$id/bulk-edit": typeof ApiSetGroupsIdBulkEditRoute;
  "/api/set-groups/$id/replace-exercise": typeof ApiSetGroupsIdReplaceExerciseRoute;
};
export type FileRoutesById = {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/exercises": typeof ExercisesRoute;
  "/logs": typeof LogsRoute;
  "/register": typeof RegisterRoute;
  "/routines": typeof RoutinesRoute;
  "/signin": typeof SigninRoute;
  "/workout": typeof WorkoutRoute;
  "/api/exercises": typeof ApiExercisesRouteWithChildren;
  "/api/gyms": typeof ApiGymsRouteWithChildren;
  "/api/routine-days": typeof ApiRoutineDaysRouteWithChildren;
  "/api/routines": typeof ApiRoutinesRouteWithChildren;
  "/api/sessions": typeof ApiSessionsRouteWithChildren;
  "/api/set-groups": typeof ApiSetGroupsRouteWithChildren;
  "/api/sets": typeof ApiSetsRouteWithChildren;
  "/api/upload": typeof ApiUploadRoute;
  "/api/user-profile": typeof ApiUserProfileRoute;
  "/api/admin/check": typeof ApiAdminCheckRoute;
  "/api/admin/exercises": typeof ApiAdminExercisesRouteWithChildren;
  "/api/admin/lookups": typeof ApiAdminLookupsRouteWithChildren;
  "/api/admin/users": typeof ApiAdminUsersRouteWithChildren;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/auth/providers": typeof ApiAuthProvidersRoute;
  "/api/dashboard/recent-sessions": typeof ApiDashboardRecentSessionsRoute;
  "/api/dashboard/stats": typeof ApiDashboardStatsRoute;
  "/api/exercises/$id": typeof ApiExercisesIdRoute;
  "/api/exercises/search": typeof ApiExercisesSearchRoute;
  "/api/exercises/similar": typeof ApiExercisesSimilarRoute;
  "/api/gyms/$id": typeof ApiGymsIdRoute;
  "/api/lookups/categories": typeof ApiLookupsCategoriesRoute;
  "/api/lookups/equipment": typeof ApiLookupsEquipmentRoute;
  "/api/lookups/muscle-groups": typeof ApiLookupsMuscleGroupsRoute;
  "/api/lookups/units": typeof ApiLookupsUnitsRoute;
  "/api/routine-days/$id": typeof ApiRoutineDaysIdRoute;
  "/api/routines/$id": typeof ApiRoutinesIdRoute;
  "/api/sessions/$id": typeof ApiSessionsIdRoute;
  "/api/sessions/current": typeof ApiSessionsCurrentRoute;
  "/api/set-groups/$id": typeof ApiSetGroupsIdRouteWithChildren;
  "/api/set-groups/reorder": typeof ApiSetGroupsReorderRoute;
  "/api/sets/$id": typeof ApiSetsIdRoute;
  "/api/sets/reorder": typeof ApiSetsReorderRoute;
  "/api/storage/$": typeof ApiStorageSplatRoute;
  "/api/uploads/$": typeof ApiUploadsSplatRoute;
  "/api/admin/exercises/$id": typeof ApiAdminExercisesIdRoute;
  "/api/admin/lookups/$id": typeof ApiAdminLookupsIdRoute;
  "/api/admin/users/$id": typeof ApiAdminUsersIdRoute;
  "/api/set-groups/$id/bulk-edit": typeof ApiSetGroupsIdBulkEditRoute;
  "/api/set-groups/$id/replace-exercise": typeof ApiSetGroupsIdReplaceExerciseRoute;
};
export type FileRouteTypes = {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/exercises"
    | "/logs"
    | "/register"
    | "/routines"
    | "/signin"
    | "/workout"
    | "/api/exercises"
    | "/api/gyms"
    | "/api/routine-days"
    | "/api/routines"
    | "/api/sessions"
    | "/api/set-groups"
    | "/api/sets"
    | "/api/upload"
    | "/api/user-profile"
    | "/api/admin/check"
    | "/api/admin/exercises"
    | "/api/admin/lookups"
    | "/api/admin/users"
    | "/api/auth/$"
    | "/api/auth/providers"
    | "/api/dashboard/recent-sessions"
    | "/api/dashboard/stats"
    | "/api/exercises/$id"
    | "/api/exercises/search"
    | "/api/exercises/similar"
    | "/api/gyms/$id"
    | "/api/lookups/categories"
    | "/api/lookups/equipment"
    | "/api/lookups/muscle-groups"
    | "/api/lookups/units"
    | "/api/routine-days/$id"
    | "/api/routines/$id"
    | "/api/sessions/$id"
    | "/api/sessions/current"
    | "/api/set-groups/$id"
    | "/api/set-groups/reorder"
    | "/api/sets/$id"
    | "/api/sets/reorder"
    | "/api/storage/$"
    | "/api/uploads/$"
    | "/api/admin/exercises/$id"
    | "/api/admin/lookups/$id"
    | "/api/admin/users/$id"
    | "/api/set-groups/$id/bulk-edit"
    | "/api/set-groups/$id/replace-exercise";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/exercises"
    | "/logs"
    | "/register"
    | "/routines"
    | "/signin"
    | "/workout"
    | "/api/exercises"
    | "/api/gyms"
    | "/api/routine-days"
    | "/api/routines"
    | "/api/sessions"
    | "/api/set-groups"
    | "/api/sets"
    | "/api/upload"
    | "/api/user-profile"
    | "/api/admin/check"
    | "/api/admin/exercises"
    | "/api/admin/lookups"
    | "/api/admin/users"
    | "/api/auth/$"
    | "/api/auth/providers"
    | "/api/dashboard/recent-sessions"
    | "/api/dashboard/stats"
    | "/api/exercises/$id"
    | "/api/exercises/search"
    | "/api/exercises/similar"
    | "/api/gyms/$id"
    | "/api/lookups/categories"
    | "/api/lookups/equipment"
    | "/api/lookups/muscle-groups"
    | "/api/lookups/units"
    | "/api/routine-days/$id"
    | "/api/routines/$id"
    | "/api/sessions/$id"
    | "/api/sessions/current"
    | "/api/set-groups/$id"
    | "/api/set-groups/reorder"
    | "/api/sets/$id"
    | "/api/sets/reorder"
    | "/api/storage/$"
    | "/api/uploads/$"
    | "/api/admin/exercises/$id"
    | "/api/admin/lookups/$id"
    | "/api/admin/users/$id"
    | "/api/set-groups/$id/bulk-edit"
    | "/api/set-groups/$id/replace-exercise";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/exercises"
    | "/logs"
    | "/register"
    | "/routines"
    | "/signin"
    | "/workout"
    | "/api/exercises"
    | "/api/gyms"
    | "/api/routine-days"
    | "/api/routines"
    | "/api/sessions"
    | "/api/set-groups"
    | "/api/sets"
    | "/api/upload"
    | "/api/user-profile"
    | "/api/admin/check"
    | "/api/admin/exercises"
    | "/api/admin/lookups"
    | "/api/admin/users"
    | "/api/auth/$"
    | "/api/auth/providers"
    | "/api/dashboard/recent-sessions"
    | "/api/dashboard/stats"
    | "/api/exercises/$id"
    | "/api/exercises/search"
    | "/api/exercises/similar"
    | "/api/gyms/$id"
    | "/api/lookups/categories"
    | "/api/lookups/equipment"
    | "/api/lookups/muscle-groups"
    | "/api/lookups/units"
    | "/api/routine-days/$id"
    | "/api/routines/$id"
    | "/api/sessions/$id"
    | "/api/sessions/current"
    | "/api/set-groups/$id"
    | "/api/set-groups/reorder"
    | "/api/sets/$id"
    | "/api/sets/reorder"
    | "/api/storage/$"
    | "/api/uploads/$"
    | "/api/admin/exercises/$id"
    | "/api/admin/lookups/$id"
    | "/api/admin/users/$id"
    | "/api/set-groups/$id/bulk-edit"
    | "/api/set-groups/$id/replace-exercise";
  fileRoutesById: FileRoutesById;
};
export type RootRouteChildren = {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  ExercisesRoute: typeof ExercisesRoute;
  LogsRoute: typeof LogsRoute;
  RegisterRoute: typeof RegisterRoute;
  RoutinesRoute: typeof RoutinesRoute;
  SigninRoute: typeof SigninRoute;
  WorkoutRoute: typeof WorkoutRoute;
  ApiExercisesRoute: typeof ApiExercisesRouteWithChildren;
  ApiGymsRoute: typeof ApiGymsRouteWithChildren;
  ApiRoutineDaysRoute: typeof ApiRoutineDaysRouteWithChildren;
  ApiRoutinesRoute: typeof ApiRoutinesRouteWithChildren;
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren;
  ApiSetGroupsRoute: typeof ApiSetGroupsRouteWithChildren;
  ApiSetsRoute: typeof ApiSetsRouteWithChildren;
  ApiUploadRoute: typeof ApiUploadRoute;
  ApiUserProfileRoute: typeof ApiUserProfileRoute;
  ApiAdminCheckRoute: typeof ApiAdminCheckRoute;
  ApiAdminExercisesRoute: typeof ApiAdminExercisesRouteWithChildren;
  ApiAdminLookupsRoute: typeof ApiAdminLookupsRouteWithChildren;
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute;
  ApiDashboardRecentSessionsRoute: typeof ApiDashboardRecentSessionsRoute;
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute;
  ApiLookupsCategoriesRoute: typeof ApiLookupsCategoriesRoute;
  ApiLookupsEquipmentRoute: typeof ApiLookupsEquipmentRoute;
  ApiLookupsMuscleGroupsRoute: typeof ApiLookupsMuscleGroupsRoute;
  ApiLookupsUnitsRoute: typeof ApiLookupsUnitsRoute;
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute;
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute;
};

declare module "@tanstack/react-router" {
  type FileRoutesByPath = {
    "/workout": {
      id: "/workout";
      path: "/workout";
      fullPath: "/workout";
      preLoaderRoute: typeof WorkoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/routines": {
      id: "/routines";
      path: "/routines";
      fullPath: "/routines";
      preLoaderRoute: typeof RoutinesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/logs": {
      id: "/logs";
      path: "/logs";
      fullPath: "/logs";
      preLoaderRoute: typeof LogsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/exercises": {
      id: "/exercises";
      path: "/exercises";
      fullPath: "/exercises";
      preLoaderRoute: typeof ExercisesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/user-profile": {
      id: "/api/user-profile";
      path: "/api/user-profile";
      fullPath: "/api/user-profile";
      preLoaderRoute: typeof ApiUserProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/upload": {
      id: "/api/upload";
      path: "/api/upload";
      fullPath: "/api/upload";
      preLoaderRoute: typeof ApiUploadRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sets": {
      id: "/api/sets";
      path: "/api/sets";
      fullPath: "/api/sets";
      preLoaderRoute: typeof ApiSetsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/set-groups": {
      id: "/api/set-groups";
      path: "/api/set-groups";
      fullPath: "/api/set-groups";
      preLoaderRoute: typeof ApiSetGroupsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sessions": {
      id: "/api/sessions";
      path: "/api/sessions";
      fullPath: "/api/sessions";
      preLoaderRoute: typeof ApiSessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/routines": {
      id: "/api/routines";
      path: "/api/routines";
      fullPath: "/api/routines";
      preLoaderRoute: typeof ApiRoutinesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/routine-days": {
      id: "/api/routine-days";
      path: "/api/routine-days";
      fullPath: "/api/routine-days";
      preLoaderRoute: typeof ApiRoutineDaysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/gyms": {
      id: "/api/gyms";
      path: "/api/gyms";
      fullPath: "/api/gyms";
      preLoaderRoute: typeof ApiGymsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/exercises": {
      id: "/api/exercises";
      path: "/api/exercises";
      fullPath: "/api/exercises";
      preLoaderRoute: typeof ApiExercisesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/uploads/$": {
      id: "/api/uploads/$";
      path: "/api/uploads/$";
      fullPath: "/api/uploads/$";
      preLoaderRoute: typeof ApiUploadsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/storage/$": {
      id: "/api/storage/$";
      path: "/api/storage/$";
      fullPath: "/api/storage/$";
      preLoaderRoute: typeof ApiStorageSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/sets/reorder": {
      id: "/api/sets/reorder";
      path: "/reorder";
      fullPath: "/api/sets/reorder";
      preLoaderRoute: typeof ApiSetsReorderRouteImport;
      parentRoute: typeof ApiSetsRoute;
    };
    "/api/sets/$id": {
      id: "/api/sets/$id";
      path: "/$id";
      fullPath: "/api/sets/$id";
      preLoaderRoute: typeof ApiSetsIdRouteImport;
      parentRoute: typeof ApiSetsRoute;
    };
    "/api/set-groups/reorder": {
      id: "/api/set-groups/reorder";
      path: "/reorder";
      fullPath: "/api/set-groups/reorder";
      preLoaderRoute: typeof ApiSetGroupsReorderRouteImport;
      parentRoute: typeof ApiSetGroupsRoute;
    };
    "/api/set-groups/$id": {
      id: "/api/set-groups/$id";
      path: "/$id";
      fullPath: "/api/set-groups/$id";
      preLoaderRoute: typeof ApiSetGroupsIdRouteImport;
      parentRoute: typeof ApiSetGroupsRoute;
    };
    "/api/sessions/current": {
      id: "/api/sessions/current";
      path: "/current";
      fullPath: "/api/sessions/current";
      preLoaderRoute: typeof ApiSessionsCurrentRouteImport;
      parentRoute: typeof ApiSessionsRoute;
    };
    "/api/sessions/$id": {
      id: "/api/sessions/$id";
      path: "/$id";
      fullPath: "/api/sessions/$id";
      preLoaderRoute: typeof ApiSessionsIdRouteImport;
      parentRoute: typeof ApiSessionsRoute;
    };
    "/api/routines/$id": {
      id: "/api/routines/$id";
      path: "/$id";
      fullPath: "/api/routines/$id";
      preLoaderRoute: typeof ApiRoutinesIdRouteImport;
      parentRoute: typeof ApiRoutinesRoute;
    };
    "/api/routine-days/$id": {
      id: "/api/routine-days/$id";
      path: "/$id";
      fullPath: "/api/routine-days/$id";
      preLoaderRoute: typeof ApiRoutineDaysIdRouteImport;
      parentRoute: typeof ApiRoutineDaysRoute;
    };
    "/api/lookups/units": {
      id: "/api/lookups/units";
      path: "/api/lookups/units";
      fullPath: "/api/lookups/units";
      preLoaderRoute: typeof ApiLookupsUnitsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/lookups/muscle-groups": {
      id: "/api/lookups/muscle-groups";
      path: "/api/lookups/muscle-groups";
      fullPath: "/api/lookups/muscle-groups";
      preLoaderRoute: typeof ApiLookupsMuscleGroupsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/lookups/equipment": {
      id: "/api/lookups/equipment";
      path: "/api/lookups/equipment";
      fullPath: "/api/lookups/equipment";
      preLoaderRoute: typeof ApiLookupsEquipmentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/lookups/categories": {
      id: "/api/lookups/categories";
      path: "/api/lookups/categories";
      fullPath: "/api/lookups/categories";
      preLoaderRoute: typeof ApiLookupsCategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/gyms/$id": {
      id: "/api/gyms/$id";
      path: "/$id";
      fullPath: "/api/gyms/$id";
      preLoaderRoute: typeof ApiGymsIdRouteImport;
      parentRoute: typeof ApiGymsRoute;
    };
    "/api/exercises/similar": {
      id: "/api/exercises/similar";
      path: "/similar";
      fullPath: "/api/exercises/similar";
      preLoaderRoute: typeof ApiExercisesSimilarRouteImport;
      parentRoute: typeof ApiExercisesRoute;
    };
    "/api/exercises/search": {
      id: "/api/exercises/search";
      path: "/search";
      fullPath: "/api/exercises/search";
      preLoaderRoute: typeof ApiExercisesSearchRouteImport;
      parentRoute: typeof ApiExercisesRoute;
    };
    "/api/exercises/$id": {
      id: "/api/exercises/$id";
      path: "/$id";
      fullPath: "/api/exercises/$id";
      preLoaderRoute: typeof ApiExercisesIdRouteImport;
      parentRoute: typeof ApiExercisesRoute;
    };
    "/api/dashboard/stats": {
      id: "/api/dashboard/stats";
      path: "/api/dashboard/stats";
      fullPath: "/api/dashboard/stats";
      preLoaderRoute: typeof ApiDashboardStatsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/dashboard/recent-sessions": {
      id: "/api/dashboard/recent-sessions";
      path: "/api/dashboard/recent-sessions";
      fullPath: "/api/dashboard/recent-sessions";
      preLoaderRoute: typeof ApiDashboardRecentSessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/providers": {
      id: "/api/auth/providers";
      path: "/api/auth/providers";
      fullPath: "/api/auth/providers";
      preLoaderRoute: typeof ApiAuthProvidersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/admin/users": {
      id: "/api/admin/users";
      path: "/api/admin/users";
      fullPath: "/api/admin/users";
      preLoaderRoute: typeof ApiAdminUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/admin/lookups": {
      id: "/api/admin/lookups";
      path: "/api/admin/lookups";
      fullPath: "/api/admin/lookups";
      preLoaderRoute: typeof ApiAdminLookupsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/admin/exercises": {
      id: "/api/admin/exercises";
      path: "/api/admin/exercises";
      fullPath: "/api/admin/exercises";
      preLoaderRoute: typeof ApiAdminExercisesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/admin/check": {
      id: "/api/admin/check";
      path: "/api/admin/check";
      fullPath: "/api/admin/check";
      preLoaderRoute: typeof ApiAdminCheckRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/set-groups/$id/replace-exercise": {
      id: "/api/set-groups/$id/replace-exercise";
      path: "/replace-exercise";
      fullPath: "/api/set-groups/$id/replace-exercise";
      preLoaderRoute: typeof ApiSetGroupsIdReplaceExerciseRouteImport;
      parentRoute: typeof ApiSetGroupsIdRoute;
    };
    "/api/set-groups/$id/bulk-edit": {
      id: "/api/set-groups/$id/bulk-edit";
      path: "/bulk-edit";
      fullPath: "/api/set-groups/$id/bulk-edit";
      preLoaderRoute: typeof ApiSetGroupsIdBulkEditRouteImport;
      parentRoute: typeof ApiSetGroupsIdRoute;
    };
    "/api/admin/users/$id": {
      id: "/api/admin/users/$id";
      path: "/$id";
      fullPath: "/api/admin/users/$id";
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport;
      parentRoute: typeof ApiAdminUsersRoute;
    };
    "/api/admin/lookups/$id": {
      id: "/api/admin/lookups/$id";
      path: "/$id";
      fullPath: "/api/admin/lookups/$id";
      preLoaderRoute: typeof ApiAdminLookupsIdRouteImport;
      parentRoute: typeof ApiAdminLookupsRoute;
    };
    "/api/admin/exercises/$id": {
      id: "/api/admin/exercises/$id";
      path: "/$id";
      fullPath: "/api/admin/exercises/$id";
      preLoaderRoute: typeof ApiAdminExercisesIdRouteImport;
      parentRoute: typeof ApiAdminExercisesRoute;
    };
  };
}

type ApiExercisesRouteChildren = {
  ApiExercisesIdRoute: typeof ApiExercisesIdRoute;
  ApiExercisesSearchRoute: typeof ApiExercisesSearchRoute;
  ApiExercisesSimilarRoute: typeof ApiExercisesSimilarRoute;
};

const ApiExercisesRouteChildren: ApiExercisesRouteChildren = {
  ApiExercisesIdRoute: ApiExercisesIdRoute,
  ApiExercisesSearchRoute: ApiExercisesSearchRoute,
  ApiExercisesSimilarRoute: ApiExercisesSimilarRoute,
};

const ApiExercisesRouteWithChildren = ApiExercisesRoute._addFileChildren(
  ApiExercisesRouteChildren,
);

type ApiGymsRouteChildren = {
  ApiGymsIdRoute: typeof ApiGymsIdRoute;
};

const ApiGymsRouteChildren: ApiGymsRouteChildren = {
  ApiGymsIdRoute: ApiGymsIdRoute,
};

const ApiGymsRouteWithChildren =
  ApiGymsRoute._addFileChildren(ApiGymsRouteChildren);

type ApiRoutineDaysRouteChildren = {
  ApiRoutineDaysIdRoute: typeof ApiRoutineDaysIdRoute;
};

const ApiRoutineDaysRouteChildren: ApiRoutineDaysRouteChildren = {
  ApiRoutineDaysIdRoute: ApiRoutineDaysIdRoute,
};

const ApiRoutineDaysRouteWithChildren = ApiRoutineDaysRoute._addFileChildren(
  ApiRoutineDaysRouteChildren,
);

type ApiRoutinesRouteChildren = {
  ApiRoutinesIdRoute: typeof ApiRoutinesIdRoute;
};

const ApiRoutinesRouteChildren: ApiRoutinesRouteChildren = {
  ApiRoutinesIdRoute: ApiRoutinesIdRoute,
};

const ApiRoutinesRouteWithChildren = ApiRoutinesRoute._addFileChildren(
  ApiRoutinesRouteChildren,
);

type ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: typeof ApiSessionsIdRoute;
  ApiSessionsCurrentRoute: typeof ApiSessionsCurrentRoute;
};

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRoute,
  ApiSessionsCurrentRoute: ApiSessionsCurrentRoute,
};

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
);

type ApiSetGroupsIdRouteChildren = {
  ApiSetGroupsIdBulkEditRoute: typeof ApiSetGroupsIdBulkEditRoute;
  ApiSetGroupsIdReplaceExerciseRoute: typeof ApiSetGroupsIdReplaceExerciseRoute;
};

const ApiSetGroupsIdRouteChildren: ApiSetGroupsIdRouteChildren = {
  ApiSetGroupsIdBulkEditRoute: ApiSetGroupsIdBulkEditRoute,
  ApiSetGroupsIdReplaceExerciseRoute: ApiSetGroupsIdReplaceExerciseRoute,
};

const ApiSetGroupsIdRouteWithChildren = ApiSetGroupsIdRoute._addFileChildren(
  ApiSetGroupsIdRouteChildren,
);

type ApiSetGroupsRouteChildren = {
  ApiSetGroupsIdRoute: typeof ApiSetGroupsIdRouteWithChildren;
  ApiSetGroupsReorderRoute: typeof ApiSetGroupsReorderRoute;
};

const ApiSetGroupsRouteChildren: ApiSetGroupsRouteChildren = {
  ApiSetGroupsIdRoute: ApiSetGroupsIdRouteWithChildren,
  ApiSetGroupsReorderRoute: ApiSetGroupsReorderRoute,
};

const ApiSetGroupsRouteWithChildren = ApiSetGroupsRoute._addFileChildren(
  ApiSetGroupsRouteChildren,
);

type ApiSetsRouteChildren = {
  ApiSetsIdRoute: typeof ApiSetsIdRoute;
  ApiSetsReorderRoute: typeof ApiSetsReorderRoute;
};

const ApiSetsRouteChildren: ApiSetsRouteChildren = {
  ApiSetsIdRoute: ApiSetsIdRoute,
  ApiSetsReorderRoute: ApiSetsReorderRoute,
};

const ApiSetsRouteWithChildren =
  ApiSetsRoute._addFileChildren(ApiSetsRouteChildren);

type ApiAdminExercisesRouteChildren = {
  ApiAdminExercisesIdRoute: typeof ApiAdminExercisesIdRoute;
};

const ApiAdminExercisesRouteChildren: ApiAdminExercisesRouteChildren = {
  ApiAdminExercisesIdRoute: ApiAdminExercisesIdRoute,
};

const ApiAdminExercisesRouteWithChildren =
  ApiAdminExercisesRoute._addFileChildren(ApiAdminExercisesRouteChildren);

type ApiAdminLookupsRouteChildren = {
  ApiAdminLookupsIdRoute: typeof ApiAdminLookupsIdRoute;
};

const ApiAdminLookupsRouteChildren: ApiAdminLookupsRouteChildren = {
  ApiAdminLookupsIdRoute: ApiAdminLookupsIdRoute,
};

const ApiAdminLookupsRouteWithChildren = ApiAdminLookupsRoute._addFileChildren(
  ApiAdminLookupsRouteChildren,
);

type ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRoute;
};

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRoute,
};

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExercisesRoute: ExercisesRoute,
  LogsRoute: LogsRoute,
  RegisterRoute: RegisterRoute,
  RoutinesRoute: RoutinesRoute,
  SigninRoute: SigninRoute,
  WorkoutRoute: WorkoutRoute,
  ApiExercisesRoute: ApiExercisesRouteWithChildren,
  ApiGymsRoute: ApiGymsRouteWithChildren,
  ApiRoutineDaysRoute: ApiRoutineDaysRouteWithChildren,
  ApiRoutinesRoute: ApiRoutinesRouteWithChildren,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSetGroupsRoute: ApiSetGroupsRouteWithChildren,
  ApiSetsRoute: ApiSetsRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiAdminCheckRoute: ApiAdminCheckRoute,
  ApiAdminExercisesRoute: ApiAdminExercisesRouteWithChildren,
  ApiAdminLookupsRoute: ApiAdminLookupsRouteWithChildren,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiDashboardRecentSessionsRoute: ApiDashboardRecentSessionsRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiLookupsCategoriesRoute: ApiLookupsCategoriesRoute,
  ApiLookupsEquipmentRoute: ApiLookupsEquipmentRoute,
  ApiLookupsMuscleGroupsRoute: ApiLookupsMuscleGroupsRoute,
  ApiLookupsUnitsRoute: ApiLookupsUnitsRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

declare module "@tanstack/react-start" {
  type Register = {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  };
}
